/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/about.vue')['default']
    Components: typeof import('./src/components/index.vue')['default']
    Contact: typeof import('./src/components/contact.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Kalandarium: typeof import('./src/components/kalandarium.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
